<?php
/**
 * build-htaccess.php - regenerates the routing block in .htaccess from
 * include/pages.php, so the routes and the registry can never drift apart.
 *
 *   php scripts/build-htaccess.php
 *
 * Only the block between the HP ROUTES markers is touched. Everything else
 * in .htaccess is left exactly as it is.
 */
chdir(__DIR__ . '/..');
require 'include/pages.php';

$pages = hp_pages();
$out = array();
$out[] = '# ===== HP ROUTES (generated by scripts/build-htaccess.php) =====';
$out[] = '# Clean, extensionless URLs. Do not hand edit: run the script.';
$out[] = '';
$out[] = '<IfModule mod_rewrite.c>';
$out[] = 'RewriteEngine On';
$out[] = 'RewriteBase /';
$out[] = '';
$out[] = '# -- 1. Canonical host. Uncomment once you have confirmed the SSL';
$out[] = '#       certificate covers the bare domain as well as www.';
$out[] = '# RewriteCond %{HTTP_HOST} ^www\.(.+)$ [NC]';
$out[] = '# RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L]';
$out[] = '# RewriteCond %{HTTPS} off';
$out[] = '# RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]';
$out[] = '';
$out[] = '# -- 2. Old .php URLs redirect once to the clean route, so the';
$out[] = '#       ranking of anything already indexed carries over.';
foreach ($pages as $file => $p) {
    $to = $p['route'] === '' ? '/' : '/' . $p['route'];
    $out[] = 'RewriteCond %{THE_REQUEST} "\s/+' . $file . '[\s?]" [NC]';
    $out[] = 'RewriteRule ^ ' . $to . ' [R=301,L]';
}
$out[] = '';
$out[] = '# -- 3. Earlier route spellings keep working, also with one hop.';
foreach ($pages as $file => $p) {
    if (empty($p['alias']) || $p['alias'] === $p['route']) continue;
    $out[] = 'RewriteRule ^' . $p['alias'] . '/?$ /' . $p['route'] . ' [R=301,L,NC]';
}
$out[] = '';
$out[] = '# -- 4. Strip a trailing slash so /contact/ and /contact are one URL.';
$out[] = 'RewriteCond %{REQUEST_FILENAME} !-d';
$out[] = 'RewriteRule ^(.+)/$ /$1 [R=301,L]';
$out[] = '';
$out[] = '# -- 5. Serve each clean route from its real file.';
foreach ($pages as $file => $p) {
    if ($p['route'] === '') continue;
    $out[] = 'RewriteRule ^' . $p['route'] . '$ ' . $file . ' [L,NC]';
}
$out[] = '';
$out[] = '# -- 6. The generated sitemap at its canonical path.';
$out[] = 'RewriteRule ^sitemap\.xml$ sitemap.php [L]';
$out[] = '';
$out[] = '# -- 7. Anything else that is a real file or folder is served as is;';
$out[] = '#       everything left over goes to the home page.';
$out[] = 'RewriteRule ^index\.php$ - [L]';
$out[] = 'RewriteCond %{REQUEST_FILENAME} !-f';
$out[] = 'RewriteCond %{REQUEST_FILENAME} !-d';
$out[] = 'RewriteRule . /index.php [L]';
$out[] = '</IfModule>';
$out[] = '# ===== END HP ROUTES =====';

$block = implode("\n", $out) . "\n";
$ht = file_get_contents('.htaccess');

// The old WordPress markers wrapped the ErrorDocument directives as well as
// the rewrite rules. Rule 7 above replaces the rewrites, but the error pages
// have to survive, so they are re-emitted rather than dropped with the block.
$keep = array();
if (preg_match_all('/^\s*ErrorDocument\s+.+$/mi', $ht, $m)) {
    foreach ($m[0] as $line) $keep[] = trim($line);
}
$ht = preg_replace('/# BEGIN WordPress.*?# END WordPress\s*/s', '', $ht);
$ht = preg_replace('/^\s*ErrorDocument\s+.+$/mi', '', $ht);

$head = array();
if ($keep) {
    $head[] = '# Custom error documents';
    $head = array_merge($head, array_unique($keep));
    $head[] = '';
}
$head[] = '# Compression and caching: both count towards Core Web Vitals,';
$head[] = '# which is a ranking input.';
$head[] = '<IfModule mod_deflate.c>';
$head[] = '  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml';
$head[] = '  AddOutputFilterByType DEFLATE application/javascript application/json';
$head[] = '  AddOutputFilterByType DEFLATE image/svg+xml';
$head[] = '</IfModule>';
$head[] = '<IfModule mod_expires.c>';
$head[] = '  ExpiresActive On';
$head[] = '  ExpiresByType text/css "access plus 1 year"';
$head[] = '  ExpiresByType application/javascript "access plus 1 year"';
$head[] = '  ExpiresByType image/jpeg "access plus 1 year"';
$head[] = '  ExpiresByType image/png "access plus 1 year"';
$head[] = '  ExpiresByType image/webp "access plus 1 year"';
$head[] = '  ExpiresByType image/svg+xml "access plus 1 year"';
$head[] = '  ExpiresByType text/html "access plus 0 seconds"';
$head[] = '</IfModule>';
$head[] = '';
$head[] = '# Includes are not pages: block direct HTTP access to them.';
$head[] = '# Guarded by module so it cannot 500 the site on older Apache.';
$head[] = '<FilesMatch "^(db|pages|seo|media|assets|header|footer|page-hero|topbar|forms|statbar|specializations|process|solution|service|counter|testimonial|why-choose|ensure|locations|faq|cta|slider|skeleton-loader|cookie-consent)\.php$">';
$head[] = '  <IfModule mod_authz_core.c>';
$head[] = '    Require all denied';
$head[] = '  </IfModule>';
$head[] = '  <IfModule !mod_authz_core.c>';
$head[] = '    Order allow,deny';
$head[] = '    Deny from all';
$head[] = '  </IfModule>';
$head[] = '</FilesMatch>';
$head[] = '';
$ht = implode("\n", $head) . "\n" . ltrim($ht);

if (preg_match('/# ===== HP ROUTES.*?# ===== END HP ROUTES =====\s*/s', $ht)) {
    $ht = preg_replace('/# ===== HP ROUTES.*?# ===== END HP ROUTES =====\s*/s', $block, $ht);
} else {
    $ht = rtrim($ht) . "\n\n" . $block;
}
file_put_contents('.htaccess', $ht);
echo "wrote .htaccess: " . count($pages) . " routes\n";
